"""Unique constraint

Revision ID: fc435a6d973b
Revises: e72d627083bb
Create Date: 2021-10-19 10:55:43.739719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc435a6d973b'
down_revision = 'e72d627083bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'saved_projects', ['project_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saved_projects', type_='unique')
    # ### end Alembic commands ###
